version: '3.7'
services:
  parity:
    container_name: custom-parity
    image: parity-custom
    build: 
      context: ../
      dockerfile: eng/parity.dockerfile
    restart: always
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp